export const ERROR_CODES = {
  NOT_ACTIVE_MISSIONARY: 'NOT_ACTIVE_MISSIONARY',
  INVALID_IDENTIFICATION: 'INVALID_IDENTIFICATION',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
