name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - beta
      - alpha
  push:
    branches:
      - dev-*
      - feature/*
      - bugfix/*

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linting
        run: pnpm run lint

      - name: Run prettier check
        run: pnpm run prettier

      - name: Run tests
        run: pnpm run test

      - name: Build project
        run: pnpm run build

      - name: Check for conventional commits
        if: github.event_name == 'pull_request'
        continue-on-error: true
        run: |
          echo "Checking commit messages for conventional format..."
          
          # Try multiple approaches to get commit range
          if git rev-parse --verify HEAD~1 > /dev/null 2>&1; then
            echo "Checking last commit only..."
            npx commitlint --from=HEAD~1 --to=HEAD --verbose
          elif git rev-parse --verify origin/${{ github.base_ref }} > /dev/null 2>&1; then
            echo "Checking commits against base branch..."
            npx commitlint --from="origin/${{ github.base_ref }}" --to=HEAD --verbose
          else
            echo "⚠️  Unable to check commit format - this is normal for new repositories"
            echo "ℹ️  For better releases, use conventional commits like:"
            echo "   feat: add new feature"
            echo "   fix: resolve bug"
            echo "   docs: update documentation"
          fi
