name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies with pnpm
        run: pnpm install

      # - name: Run tests
      #   run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Debian SSH machine
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_HOST_USERNAME }}
          key: ${{ secrets.SSH_HOST_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_HOST_PASSPHRASE }}
          script: |
            eval "$(ssh-agent -s)"
            echo "Adding SSH key"
            echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -
            cd entrelazos-frontend
            git pull origin main
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install
            npm run build
            sudo cp -r dist/* /var/www/html/entrelazos-react/
